accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("", views.accounts_root, name="root"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    # path("email/", views.test_mail, name="mail"),
    path("edit/", views.profile_edit, name="profile_edit"),
    path("password_change/", views.password_change, name="password_change"),
    re_path(r"^(?P<username>[\w.@+-]+)/follow/$", views.user_follow, name="user_follow"),
    re_path(r"^(?P<username>[\w.@+-]+)/unfollow/$", views.user_unfollow, name="user_unfollow"),
]

instagram/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.validators import UnicodeUsernameValidator

app_name = "instagram"

urlpatterns = [
    path("", views.index, name="root"),
    path("post/new/", views.post_new, name="post_new"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    re_path(r"^(?P<username>[\w.@+-]+)/$", views.user_page, name="user_page"),
    path("post/<int:pk>/like/", views.post_like, name="post_like"),
    path("post/<int:pk>/unlike/", views.post_unlike, name="post_unlike"),
    # 코멘트
    path("post/<int:post_pk>/comment/new/", views.comment_new, name="comment_new"),
]

instagram/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import re


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(models.Model):
    # date 기본 정보
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # post 핵심기능
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="my_post_set",  # user.my_post_set
    )
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d")
    caption = models.TextField(max_length=500)
    location = models.CharField(max_length=100)

    # tag 관련
    tag_set = models.ManyToManyField("Tag", blank=True)

    # 좋아요 기능
    like_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="like_post_set",  # user.like_post_set
    )

    def __str__(self):
        return self.caption

    @property
    def author_name(self):
        return f"{self.author.name}"

    def get_absolute_url(self):
        return reverse("instagram:post_detail", kwargs={"pk": self.pk})

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        return tag_list

    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering = ["-id"]


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        ordering = ["-id"]

instagram/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "photo",
            "caption",
            "location",
        ]
        widgets = {
            "caption": forms.Textarea,
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]
        widgets = {
            "message": forms.Textarea(
                attrs={
                    "rows": 2,
                }
            ),
        }

instagram/views.py
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, render, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.contrib.auth import get_user_model, get_user
from .models import Tag, Post
from django.db.models import Q
import logging

from datetime import timedelta
from django.utils import timezone

logger = logging.getLogger("django.server")


@login_required
def index(request):

    post_list = (
        Post.objects.all()
        .filter(Q(author__in=request.user.following_set.all()) | Q(author=request.user))
        .filter(created_at__gte=timezone.now() - timedelta(days=3))
    )

    suggested_user_list = (
        get_user_model()
        .objects.all()
        .exclude(pk=request.user.pk)
        .exclude(pk__in=request.user.following_set.all())[:3]
    )
    comment_form = CommentForm()

    return render(
        request,
        "instagram/index.html",
        {
            "suggested_user_list": suggested_user_list,
            "post_list": post_list,
            "comment_form": comment_form,
        },
    )


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)

        logger.warning(str(request))

        if form.is_valid():
            post = form.save(commit=False)
            # post.tag_set
            post.author = get_user(request)
            post.save()
            post.tag_set.add(*post.extract_tag_list())

            messages.success(request, "포스팅을 저장하였습니다.")
            return redirect(post)
            # return redirect(post)
        else:
            post = PostForm(request.POST, request.FILES)

    else:
        form = PostForm()

    return render(
        request,
        "instagram/post_form.html",
        {
            "form": form,
        },
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()

    return render(
        request,
        "instagram/post_detail.html",
        {
            "post": post,
            "comment_form": comment_form,
        },
    )


def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)

    if request.user.is_authenticated:
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count()  # 실제 데이터베이스에 count 쿼리
    # len(post_list_count) 쓰지 마세요

    return render(
        request,
        "instagram/user_page.html",
        {
            "page_user": page_user,
            "post_list": post_list,
            "post_list_count": post_list_count,
            "is_follow": is_follow,
        },
    )


def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    messages.success(request, f"좋아요를 눌렀습니다. #post-{post.pk}")
    return redirect(request.META.get("REFFERER", "root"))


def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, f"좋아요를 취소했습니다. #post-{post.pk}")
    return redirect(request.META.get("REFFERER", "root"))


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

            if request.is_ajax():
                return render(
                    request,
                    "instagram/_comment.html",
                    {
                        "comment": comment,
                    },
                )

            return redirect(comment.post)
    else:
        form = CommentForm()

    return render(
        request,
        "instagram/comment_form.html",
        {
            "form": form,
        },
    )

instagram/templates/instagram/_comment.html
{% load humanize instagram_tags %}

<div class="comment">
    <strong>{{ comment.author }}</strong>
    {{ comment.message }}
    <small class="text-muted">{{ comment.created_at|naturaltime }}</small>
</div>

instagram/templates/instagram/_form.html
{% load bootstrap4 %}

<div class="card" style="width: 18rem;">
    {% if label %}
    <div class="card-header">
        <p>{{ label }}</p>
    </div>
    {% endif %}
    <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form%}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {{ label|default:"Submit" }}
                    </button>
                {% endbuttons %}
            {% else %}
                <div class="alert alert-error">
                    form 객체를 지정해주세요
                </div>
            {% endif %}
            
        </form>
        </ul>
    </div>
</div>

instagram/templates/instagram/_post_card.html
{% load humanize instagram_tags %}
{% load bootstrap4 %}

<div class="card">
    <div class="card-header">
        <img src="{{ post.author.avatar_url }}" alt="" srcset="" style="width: 3rem">
        <a href="{% url "instagram:user_page" post.author %}">
            {{ post.author }}
        </a>
        {{ post.author.name }}
    </div>
    <div class="card-body">

        <div>
            <img src="{{ post.photo.url }}" alt="" srcset="" style="width: 100%">
            {% for tag in post.tag_set.all %}
                <span class="badge bg-primary">{{ tag.name }}</span>
            {% endfor %}
        </div>

        <div id="post-{{ post.pk }}-comment-list" class="comment-list my-3">
            {% for comment in post.comment_set.all %}
                {% include "instagram/_comment.html" %}
            {% endfor %}
        </div>
    
        <div>
            {% if post|is_like_user:user %}
                <a href="{% url "instagram:post_unlike" post.pk %}" style="color: inherit;"><i class="fas fa-heart"></i></a>
            {% else %}
                <a href="{% url "instagram:post_like" post.pk %}" style="color: inherit;"><i class="far fa-heart"></i></a>
            {% endif %}
        </div>
        <div>
            <a href="{{ post.get_absolute_url }}" style="" class="text-muted">
                {{ post.created_at|naturaltime }}
            </a>
        </div>
    
    </div>
    
    <div class="card-footer">
        <a href="{% url "instagram:comment_new" post.pk %}">댓글 쓰기</a>
        <form id="post-{{post.pk}}-comment-form" action="{% url "instagram:comment_new" post.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" name="" value="댓글 쓰기" class="btn btn-primary btn-block">
            <button>댓글쓰기</button>
        </form>

        <div id="server-response-{{ post.pk }}">

        </div>

        <script>
        jQuery(function(){
            var form_id = "post-{{post.pk}}-comment-form";
            jQuery("#" + form_id).submit(function(e) {
                e.preventDefault();

                var options = {
                    // target: "#server-response-{{ post.pk }}",
                    success: function(responseText, statusText, xhr, $form) {
                        console.group("ajaxSubmit response");
                        console.log(responseText);
                        console.log(statusText);
                        console.log(xhr);
                        console.log($form);
                        console.groupEnd();

                        $("#post-11-comment-list").prepend(responseText);
                    }
                };

                $(this).ajaxSubmit(options);

                console.log("submit!!");
                return false;
            });
            console.log("document ready");
        });
        </script>
    </div>
</div>

instagram/templates/instagram/comment_form.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-2">

                {% include "instagram/_form.html" with lable="댓글 쓰기" %}
                
            </div>
        </div>
    </div>

{% endblock content %}

instagram/templates/instagram/index.html
{% extends "instagram/layout.html"%}

{% block content %}
    <h1>Instagram</h1>
    <hr>
    <a href="{% url "instagram:post_new" %}" class="btn btn-primary">새 포스트 쓰기</a>

    <div class="container">
        <div class="row">
            <div class="col-8">
                timeline
                <hr>
                {% for post in post_list %}
                    <div class="mb-3">
                        {% include "instagram/_post_card.html" %}
                    </div>
                {% empty %}
                    포스팅이 없습니다.
                {% endfor %}
            </div>
            <div class="col-4">
                {% include "instagram/timeline_sidebar.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/layout.html
{% extends "layout.html" %}

{% block content %}
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% include "instagram/_post_card.html" %}
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-2">

                {% include "instagram/_form.html" with lable="새포스팅 쓰기" %}
                
            </div>
        </div>
    </div>

{% endblock content %}

instagram/templates/instagram/timeline_sidebar.html
<div class="d-flex justify-content-start align-items-center p-2">
    <div>
        <img src="{{ user.avatar_thumbnail.url }}" alt="" srcset="" class="rounded-circle">
    </div>
    <div class="d-flex flex-column justify-content-center align-items-start ps-3">
        <div class="">{{ user.name }}</div>
        <small class="text-muted">{{ user.username }}</small>
    </div>    
</div>

<div class="card">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card_body p-4">
        Stories from people you follow will show up here.
    </div>
</div>

<div class="card">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card_body p-4">
    {% for suggested_user in suggested_user_list %}
        {% include "instagram/timeline_sidebar_user_follow.html" %}
    {% empty %}
        추천 친구가 없습니다.
    {% endfor %}
    </div>
</div>

instagram/templates/instagram/timeline_sidebar_user_follow.html
<div class="d-flex m-1">
    <div class="p-1">
        <img src="{{ suggested_user.avatar_url }}" alt="" srcset="" style="width:32px; height:32px;" class="rounded-circle">
    </div>
    <div class="p-1">
        <a href="{% url "instagram:user_page" suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="p-1 ms-auto text-muted">
        <a href="{% url "accounts:user_follow" suggested_user.username %}">Follow</a>
    </div>
</div>

instagram/templates/instagram/user_page.html
{% extends "instagram/layout.html" %}
{% load thumbnail %}

{% block content %}

    <div class="row">
        <div class="col-3" style="text-align: center;">
            <img src="{{ page_user.avatar_url }}" alt="" srcset="" class="rounded-circle" style="width: 100%">
        </div>
        <div class="col-9">
            {{ page_user.username }}
            <a href="{% url "accounts:profile_edit" %}" class="btn btn-second">Edit Profile</a>
            
            {% if is_follow %}
                <a href="{% url "accounts:user_unfollow" page_user.username %}">Unfollow</a>
            {% else %}
                <a href="{% url "accounts:user_follow" page_user.username %}">follow</a>
            {% endif %}

            <hr>
            {{ post_list_count }} posts, 0 followers, 0 following
            <hr>
            {{ page_user.name }}
        </div>
        {%  for post in post_list %}
            <div class="col-2 mb-5">
                <img src="{{ post.photo.url }}" alt="" srcset="" style="width: 100%">
                <img src="{% thumbnail post.photo 256x256 crop %}" alt="" srcset="" style="width: 100%">
            </div>
        {% endfor %}
    </div>

{% endblock content %}