accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("", views.accounts_root, name="root"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    # path("email/", views.test_mail, name="mail"),
    path("edit/", views.profile_edit, name="profile_edit"),
    path("password_change/", views.password_change, name="password_change"),
    re_path(r"^(?P<username>[\w.@+-]+)/follow/$", views.user_follow, name="user_follow"),
    re_path(r"^(?P<username>[\w.@+-]+)/unfollow/$", views.user_unfollow, name="user_unfollow"),
]

asklecture/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
import debug_toolbar
from django.views.generic import TemplateView, RedirectView
import django_pydenticon
from django_pydenticon.views import image as pydenticon_image

urlpatterns = [
    path("admin/", admin.site.urls),
    path("identicon/image/<path:data>/", pydenticon_image, name="pydenticon_image"),
    path("accounts/", include("accounts.urls")),
    path("instagram/", include("instagram.urls")),
    path("", RedirectView.as_view(pattern_name="instagram:root"), name="root"),
]

if settings.DEBUG:

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asklecture/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static "bootstrap-5.0.0-beta1-dist/css/bootstrap.css" %}">
    
    <script src="{% static "jquery-3.5.1.min.js" %}"></script>
    <script src="{% static "jquery.form-3.51.0.js" %}"></script>
    <script src="{% static "bootstrap-5.0.0-beta1-dist/js/bootstrap.min.js"%}"></script>
    
</head>
<body>
    {% if messages %}
        {% for message in messages %}
        <div class="alert border alert-{{ message.tags }}">
            {{ message }}    
        </div>
        {% endfor %}
    {% endif %}


    <header class="d-flex flex-row justify-content-between align-items-center border p-3">
        <a href="{% url "root" %}">
            <img src="{% static "logo.png" %}" style="width: 10rem" alt="" srcset="">
        </a>
        <div class="d-flex flex-row align-items-center border">검색하기</div>
        <nav class="my-2 my-md-0 me-md-3">
            <a class="" style="text-decoration: none;" href="#">
                <svg aria-label="홈" class="" fill="#262626" height="22" viewBox="0 0 48 48" width="22"><path d="M45.5 48H30.1c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2.1-4.6-4.6-4.6s-4.6 2.1-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.6-.6 2.1 0l21.5 21.5c.3.3.4.7.4 1.1v23.5c.1.8-.6 1.5-1.4 1.5z"></path></svg>
            </a>
            <a class="" style="text-decoration: none;" href="#">
                <svg aria-label="사람 찾기" class="" fill="#262626" height="22" viewBox="0 0 48 48" width="22"><path clip-rule="evenodd" d="M24 0C10.8 0 0 10.8 0 24s10.8 24 24 24 24-10.8 24-24S37.2 0 24 0zm0 45C12.4 45 3 35.6 3 24S12.4 3 24 3s21 9.4 21 21-9.4 21-21 21zm10.2-33.2l-14.8 7c-.3.1-.6.4-.7.7l-7 14.8c-.3.6-.2 1.3.3 1.7.3.3.7.4 1.1.4.2 0 .4 0 .6-.1l14.8-7c.3-.1.6-.4.7-.7l7-14.8c.3-.6.2-1.3-.3-1.7-.4-.5-1.1-.6-1.7-.3zm-7.4 15l-5.5-5.5 10.5-5-5 10.5z" fill-rule="evenodd"></path></svg>
            </a>
            <a class="" style="text-decoration: none;" href="#">
                <svg aria-label="활동 피드" class="" fill="#262626" height="22" viewBox="0 0 48 48" width="22"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
            </a>
            {% if user.username %}
                {{ user.username }}
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" style="width: 3rem; height: 3rem;">
                    <img src="{{ user.avatar_thumbnail.url }}" >
                    <img src="{% url "pydenticon_image" user.username %}" style="height: 3rem">
                {% else %}
                    <a class="" style="text-decoration: none;" href="{% url "accounts:profile_edit" %}">
                        <img src="{% url "pydenticon_image" user.username %}" style="height: 3rem">
                    </a>
                {% endif %}
            {% endif %}
            <a class="btn btn-outline-primary" href="{% url "accounts:signup" %}">
                Sign up
            </a>
            {% if user.username %}
            <a class="btn btn-outline-primary" href="{% url "accounts:logout" %}">
                Logout
            </a>
            {% else %}
            <a class="btn btn-outline-primary" href="{% url "accounts:login" %}?next={% url "accounts:root" %}">
                Login
            </a>
            {% endif %}
        </nav>
    </header>

    {% block content %}
    {% endblock content %}
    
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">© 2017-2021</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Cool stuff</a></li>
            <li><a class="link-secondary" href="#">Random feature</a></li>
            <li><a class="link-secondary" href="#">Team feature</a></li>
            <li><a class="link-secondary" href="#">Stuff for developers</a></li>
            <li><a class="link-secondary" href="#">Another one</a></li>
            <li><a class="link-secondary" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Resource</a></li>
            <li><a class="link-secondary" href="#">Resource name</a></li>
            <li><a class="link-secondary" href="#">Another resource</a></li>
            <li><a class="link-secondary" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
            <li><a class="link-secondary" href="#">Team</a></li>
            <li><a class="link-secondary" href="#">Locations</a></li>
            <li><a class="link-secondary" href="#">Privacy</a></li>
            <li><a class="link-secondary" href="#">Terms</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

asklecture/templates/root.html
None